### ISSUE TITLE
Épico 4 - Disparo por Score

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/lead-score#46]
Objetivo:
Implementar um sistema automatizado que envie as leads com o calculo para webhook

Principal Entrega: 
Entregar as leads selecionada para os webhooks selecionados

Critérios de Aceitação:

Historias:
- [ ] Registrar as regras de score para envio
- [ ] Permitir o envio individual
- [ ] Permitir visualizar o histórico de envios
